# Generated by Django 3.2.3 on 2021-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_token',
            field=models.CharField(blank=True, default='XiR39WYu', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.BinaryField(),
        ),
    ]
