# Generated by Django 3.2.3 on 2021-09-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210907_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='https://www.pngitem.com/pimgs/m/146-1468479_my-profile-icon-blank-profile-picture-circle-hd.png', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
