# Generated by Django 3.2.3 on 2021-09-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
