# Generated by Django 3.2.3 on 2021-09-11 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20210911_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
