# Generated by Django 3.2.3 on 2021-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20210914_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
